version: '3.9'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      ConnectionStrings__NetstrDatabase: Host=db;Database=Netsrt;Username=Netstr;Password=Netstr
    depends_on: 
      - db
  db:
    image: "postgres:16-alpine"
    restart: always
    environment:
      POSTGRES_PASSWORD: Netstr
      POSTGRES_USER: Netstr
      POSTGRES_DB: Netstr