name: netstr-relay-${NETSTR_ENVIRONMENT:-prod}

services:
  app:
    image: "${NETSTR_IMAGE:-bezysoftware/netstr:latest}"
    restart: always
    ports:
      - "${NETSTR_PORT:-8080}:8080"
    environment:
      ConnectionStrings__NetstrDatabase: Host=db:5432;Database=Netsrt;Username=Netstr;Password=${NETSTR_DB_PASSWORD:?Password must be set}
      ASPNETCORE_ENVIRONMENT: ${NETSTR_ENVIRONMENT_LONG}
    depends_on: 
      - db
    volumes:
      - /data/${NETSTR_ENVIRONMENT:-prod}/netstr/logs:/app/logs
  db:
    image: "postgres:16-alpine"
    restart: always
    environment:
      POSTGRES_PASSWORD: ${NETSTR_DB_PASSWORD:?Password must be set}
      POSTGRES_USER: Netstr
      POSTGRES_DB: Netstr
    volumes:
      - /data/${NETSTR_ENVIRONMENT:-prod}/postgres:/var/lib/postgresql/data
