name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.tag.outputs.IMAGE_TAG }}
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: bezysoftware
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get docker tag
        id: tag
        run: echo "IMAGE_TAG=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile.Release
          builder: ${{ steps.buildx.outputs.name }}
          build-args: |
            APP_VERSION=${{ steps.tag.outputs.IMAGE_TAG }}
          push: true
          tags: bezysoftware/netstr:${{ steps.tag.outputs.IMAGE_TAG }},bezysoftware/netstr:latest

  deploy:
    runs-on: ubuntu-latest
    needs: [ release ]
    environment: prod
    env:
      IMAGE_TAG: ${{ needs.release.outputs.image-tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup SSH
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Create docker context
        run: docker context create remote --docker "host=ssh://${{ secrets.SSH_USER }}@${{ secrets.SSH_REMOTE_HOST }}"
        
      - name: Docker compose up
        run: |
          docker --context remote compose pull
          docker --context remote compose up -d
        env:
          NETSTR_DB_PASSWORD: ${{ secrets.NETSTR_DB_PASSWORD }}
          NETSTR_IMAGE: "bezysoftware/netstr:${{ env.IMAGE_TAG }}"
          NETSTR_ENVIRONMENT: prod
          NETSTR_PORT: 8080
          NETSTR_VERSION: ${{ env.IMAGE_TAG }}